### ISSUE TITLE
feature request: blend multiple sounds

### ISSUE THREAD

**Issue by ivan-aksamentov** [costales/anoise#1]
It would be great if Anoise could mix multiple sound tracks, with a possibility of adjusting volume level of each. For example, user might want to listen for fireplace sound at full volume and overlay some less loud rain and thunder sounds on top. This would allow to create more complex and  more realistic sound environments.

The simplest implementation would be to run multiple copies of Anoise process simultaneously.
In Anoise UI it could be implemented, for example, by adding a "+" button in the user interface, that would create additional copies of the sound widget, with its own sound picker and volume slider.

For demonstration, an example of online application that has sound mixer feature is Noisli (https://www.noisli.com)

P.S. Thank you for your great software!

**Comment by costales** [comment]
Hi,
Thanks for the feedback, but the idea of ANoise is to be a so so so simple UI.
I'll think on that.
A hug.
