### ISSUE TITLE
anoise-ui problem

### ISSUE THREAD

**Issue by dimzon** [costales/anoise#2]
dpkg: error processing archive /var/cache/apt/archives/anoise-gui_0.0.4_all.deb (--unpack):
 trying to overwrite '/usr/share/anoise/anoise.ui', which is also in package anoise 0.0.30
Errors were encountered while processing:
 /var/cache/apt/archives/anoise-gui_0.0.4_all.deb

**Comment by costales** [comment]
Hi,
Could you uninstall the previous version?
sudo apt remove anoise-gui
Best regards.
