### ISSUE TITLE
unmet dependencies in ubuntu 20.04

### ISSUE THREAD

**Issue by perebalazs** [costales/anoise#3]
Is not installable in ubuntu 20.04. It says:

The following packages have unmet dependencies:
 anoise : Depends: python-gst-1.0 but it is not installable
          Depends: gir1.2-webkit-3.0 but it is not installable
          Depends: anoise-media but it is not installable

ppa is also not working:
Err:6 http://ppa.launchpad.net/costales/anoise/ubuntu focal Release                                                                        
  404  Not Found [IP: 91.189.95.83 80]

The repository 'http://ppa.launchpad.net/costales/anoise/ubuntu focal Release' does not have a Release file.

**Comment by costales** [comment]
Thanks for the feedback @perebalazs !

I have to rebuild it for these new packages: `python3-gst-1.0` and `gir1.2-webkit2-4.0`.

Working on it.

A hug

**Comment by costales** [comment]
Hi, this should work now (release 0.0.36) :) Best regards and thanks for the feedback!
