### ISSUE TITLE
Feature Request - add extra ambient noises from directory

### ISSUE THREAD

**Issue by guiverc** [costales/anoise#5]
I have a directory where I've got some ambient noise files. I'd like a feature to add file(s) or better a directory of files.

And thanks for creating this program, I love it.

**Comment by alexandrebarbaruiva** [comment]
You can create a `~/.ANoise` folder and add all your files!

**Comment by costales** [comment]
Hi, as @alexandrebarbaruiva said, that is the way :) A hug.
